# 2.2 Метод Гаусса с выбором главного элемента по строке

Миллер Владимир (696а)

In [4]:
import numpy as np

N = 2

In [2]:
def solve(A, b):
    """ 
    Решает систему Ax=b методом Гаусса с выбором главного элемента по строке.
    Возвращает матрицы и вектор решения: L, U, Q, x
    AQ=LU
    """
    n = A.shape[0]
    
    # Вычисление матриц L, U, Q.
    U = np.copy(A)
    L = np.eye(n)
    Q = np.eye(n, dtype=int)
    for k in range(n - 1):
        i = k + np.argmax(np.abs(U[k, k:n]))
        U[:, k], U[:, i] = U[:, i], U[:, k].copy()
        Q[:, k], Q[:, i] = Q[:, i], Q[:, k].copy()
        for j in range(k + 1, n):
            L[j, k] =  U[j, k] / U[k, k]
            U[j, k:n] = U[j, k:n] - L[j, k] * U[k, k:n]
    
    # Решение системы Lz=b (прямая подстановка).
    z = np.zeros(n)
    for i in range(n):
        z[i] = b[i]
        for j in range(i):
            z[i] -= L[i, j] * z[j]
            
    # Решение системы Uy=z (обратная подстановка).
    y = np.zeros(n)
    for i in reversed(range(n)):
        y[i] = z[i]
        for j in range(i + 1, n):
            y[i] -= U[i, j] * y[j]
        y[i] /= U[i, i]
        
    # Финальное решение (x=Qy).
    x = np.zeros(n)
    for i in range(n):
        for j in range(n):
            if Q[i, j] == 1:
                x[i] = y[j]
    
    return L, U, Q, x

In [5]:
A = np.random.rand(N, N)
b = np.random.rand(N)

x_lib = np.linalg.solve(A, b)
L, U, Q, x = solve(A, b)

print(np.linalg.norm(x_lib - x))

5.551115123125783e-17


In [6]:
A

array([[0.26561928, 0.46603656],
       [0.75637236, 0.05779312]])

In [7]:
b

array([0.29356195, 0.56698188])

In [8]:
x_lib

array([0.73341601, 0.21189865])

In [9]:
x

array([0.73341601, 0.21189865])

In [18]:
A = np.eye(2)
A[0, 1] = np.random.uniform(low=-2, high=2, size=(1,))
A[1, 0] = np.random.uniform(low=0, high=4, size=(1,))
b = np.random.rand(N)

x_lib = np.linalg.solve(A, b)
L, U, Q, x = solve(A, b)

print(np.linalg.norm(x_lib - x))

5.721958498152797e-17


In [19]:
A

array([[ 1.        , -0.61485293],
       [ 3.59567492,  1.        ]])

In [20]:
b

array([0.35116953, 0.03587334])

In [21]:
x_lib

array([ 0.11624052, -0.38208977])

In [22]:
x

array([ 0.11624052, -0.38208977])